### ISSUE TITLE
DivIcon symbol cannot be resolved from module 'svelte-leafletjs' when using TypeScript

### ISSUE THREAD

**Issue by kegbuna** [ngyewch/svelte-leafletjs#33]
![image](https://github.com/ngyewch/svelte-leaflet/assets/3621660/a8dba821-8664-4832-9dcc-b5e6ac9c9bc3)

It should be noted that the DivIcon component works great, it is just that it seems to be missing from the types file.

If I could have instructions on how to resolve this there are some other type issues I would like to look at as well, such as event handlers.

**Comment by kegbuna** [comment]
I found the package in the DefinitelyTyped repository. I will try to update there.

**Comment by jieter** [comment]
This is fixed by @kegbuna's PR DefinitelyTyped/DefinitelyTyped#67589 and can be closed.
