### ISSUE TITLE
Bundling with exposing .svelte files possible?

### ISSUE THREAD

**Issue by jerch** [ngyewch/svelte-leafletjs#39]
We currently have issues to use your great lib in an SPA project (all client side rendered). The situation is the following:
- A route contains a page with list entries that are clickable and lead to subroutes containing `<LeafletMap>` views.
- The top route and the subroutes are directly accessible via URL, thus load directly the (sub) pages views.
- When accessing the top route first and then navigating to the subpages with the maps - everything works fine, the maps are loading properly.
- **Issue:** A direct URL call to a subpage crashes deep inside svelte with this error:
  ```
  Uncaught (in promise) TypeError: block.l is not a function
      claim_component Component.js:38
      claim water_segments_map.svelte:710
      claim_component Component.js:38
      claim +page.svelte:707
      claim +page.svelte:123
      claim +page.svelte:2562
      claim_component Component.js:38
      claim root.svelte:268
  ```

Debugging the error was really cumbersome, as it happens deep within svelte with no sourcemaps. After some messing around with breakpoints and stack inspection it turned out, that svelte failed to process the main `<div>` of the `<LeafletMap>` component. So we removed all custom code and applied your test demo, which also did not work. Next we forked `svelte-leafletjs` and made sure to build it with the same versions as our project - svelte@4.2.12 / typescript@5.4.2 / vite@5.1.6. Again this did not work.
At this point we were a bit clueless about the source of the error and had only the gut feeling left, that something with the bundling of `svelte-leafletjs` breaks with expectations of svelte on import side. So we checked your bundling output `dist/svelte-leafletjs.js` and found it containing compiled code instead of exporting .svelte files.
Suspicous of a possible "ABI" compat issue we went ahead and rebundled your package with exposing .svelte files and yep - that worked.

This is what we changed:
```diff
diff --git a/package.json b/package.json
index 2e932f8..020f1ce 100644
--- a/package.json
+++ b/package.json
@@ -11,7 +11,7 @@
   "type": "module",
   "scripts": {
     "doDev": "vite",
-    "doBuild": "cross-env NODE_ENV=production vite build",
+    "doBuild": "svelte-package -i src",
     "doPreview": "vite preview",
     "check": "svelte-check --tsconfig ./tsconfig.json --compiler-warnings a11y-click-events-have-key-events:ignore",
     "watch:check": "svelte-check --tsconfig ./tsconfig.json --watch --compiler-warnings a11y-click-events-have-key-events:ignore",
@@ -20,6 +20,7 @@
     "preview": "run-s build doPreview"
   },
   "devDependencies": {
+    "@sveltejs/package": "^2.3.0",
     "@sveltejs/vite-plugin-svelte": "^3.0.2",
     "@tsconfig/svelte": "^5.0.2",
     "@types/geojson": "^7946.0.14",
@@ -39,13 +40,13 @@
     "svelte",
     "leaflet"
   ],
-  "module": "./dist/svelte-leafletjs.js",
-  "svelte": "./dist/svelte-leafletjs.js",
+  "module": "./dist/index.js",
+  "svelte": "./dist/index.js",
   "exports": {
     ".": {
-      "import": "./dist/svelte-leafletjs.js",
+      "import": "./dist/index.js",
       "types": "./src/index.d.ts",
-      "svelte": "./dist/svelte-leafletjs.js"
+      "svelte": "./dist/index.js"
     }
   }
 }
```
Difference:
`@sveltejs/package` exposes the .svelte files, so the target project does not seen precompiled output anymore, but the svelte source and can do the compiling itself. This seems to be the suggested way to create svelte libs to be used in other projects.

So question is - could you change the bundle output to expose .svelte files directly? There are no unit tests in the repo, so we are not sure how to test things. At least it works in our project with that change as expected. Currently we cannot use your bundled package because of the error above.

**Comment by jerch** [comment]
@ngyewch Created PR #40 dealing with our issue.

**Comment by ngyewch** [comment]
@jerch Thanks for the PR!
